export const DEPARTAMENTOS = [
  { code: '', label: 'Selecciona departamento' },
  { code: 'AMA', label: 'Amazonas' },
  { code: 'ANT', label: 'Antioquia' },
  { code: 'ARA', label: 'Arauca' },
  { code: 'ATL', label: 'Atlántico' },
  { code: 'BOL', label: 'Bolívar' },
  { code: 'BOY', label: 'Boyacá' },
  { code: 'CAL', label: 'Caldas' },
  { code: 'CAQ', label: 'Caquetá' },
  { code: 'CAS', label: 'Casanare' },
  { code: 'CAU', label: 'Cauca' },
  { code: 'CES', label: 'Cesar' },
  { code: 'CHO', label: 'Chocó' },
  { code: 'COR', label: 'Córdoba' },
  { code: 'CUN', label: 'Cundinamarca' },
  { code: 'DC', label: 'Bogotá D.C.' },
  { code: 'GUA', label: 'Guainía' },
  { code: 'GUV', label: 'Guaviare' },
  { code: 'HUI', label: 'Huila' },
  { code: 'LAG', label: 'La Guajira' },
  { code: 'MAG', label: 'Magdalena' },
  { code: 'MET', label: 'Meta' },
  { code: 'NAR', label: 'Nariño' },
  { code: 'NSA', label: 'Norte de Santander' },
  { code: 'PUT', label: 'Putumayo' },
  { code: 'QUI', label: 'Quindío' },
  { code: 'RIS', label: 'Risaralda' },
  { code: 'SAP', label: 'San Andrés y Providencia' },
  { code: 'SAN', label: 'Santander' },
  { code: 'SUC', label: 'Sucre' },
  { code: 'TOL', label: 'Tolima' },
  { code: 'VAC', label: 'Valle del Cauca' },
  { code: 'VAU', label: 'Vaupés' },
  { code: 'VID', label: 'Vichada' },
];

export const CITIES_BY_DEPT = {
  'AMA': ['Leticia', 'Puerto Nariño'],
  'ANT': ['Medellín', 'Bello', 'Itagüí', 'Envigado', 'Apartadó', 'Rionegro', 'Turbo', 'Caucasia', 'Caldas', 'Chigorodó', 'Sabaneta', 'Copacabana', 'La Estrella', 'Marinilla', 'Guarne', 'Carmen de Viboral', 'La Ceja'],
  'ARA': ['Arauca', 'Arauquita', 'Saravena', 'Tame'],
  'ATL': ['Barranquilla', 'Soledad', 'Malambo', 'Sabanalarga', 'Baranoa', 'Puerto Colombia', 'Galapa'],
  'BOL': ['Cartagena', 'Magangué', 'Turbaco', 'El Carmen de Bolívar', 'Arjona', 'Mompós'],
  'BOY': ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Puerto Boyacá', 'Paipa', 'Garagoa'],
  'CAL': ['Manizales', 'La Dorada', 'Villamaría', 'Chinchiná', 'Riosucio', 'Salamina'],
  'CAQ': ['Florencia', 'San Vicente del Caguán', 'Cartagena del Chairá', 'Puerto Rico'],
  'CAS': ['Yopal', 'Aguazul', 'Paz de Ariporo', 'Villanueva'],
  'CAU': ['Popayán', 'Quilichao', 'El Tambo', 'Puerto Tejada', 'Piendamó'],
  'CES': ['Valledupar', 'Aguachica', 'Agustín Codazzi', 'Bosconia'],
  'CHO': ['Quibdó', 'Istmina', 'Condoto'],
  'COR': ['Montería', 'Lorica', 'Tierralta', 'Cereté', 'Sahagún', 'Montelíbano'],
  'CUN': ['Bogotá D.C.', 'Soacha', 'Facatativá', 'Chía', 'Zipaquirá', 'Mosquera', 'Madrid', 'Funza', 'Fusagasugá', 'Tocancipá', 'Cajicá', 'Girardot'],
  'DC': ['Bogotá D.C.'],
  'GUA': ['Inírida'],
  'GUV': ['San José del Guaviare'],
  'HUI': ['Neiva', 'Pitalito', 'Garzón', 'La Plata'],
  'LAG': ['Riohacha', 'Maicao', 'San Juan del Cesar', 'Fonseca'],
  'MAG': ['Santa Marta', 'Ciénaga', 'Fundación', 'El Banco', 'Plato'],
  'MET': ['Villavicencio', 'Acacías', 'Granada', 'Puerto López', 'Restrepo'],
  'NAR': ['Pasto', 'Tumaco', 'Ipiales', 'Túquerres'],
  'NSA': ['Cúcuta', 'Ocaña', 'Villa del Rosario', 'Los Patios', 'Tibú', 'Pamplona'],
  'PUT': ['Mocoa', 'Puerto Asís', 'Orito', 'Valle del Guamuez'],
  'QUI': ['Armenia', 'Calarcá', 'Circasia', 'Tebaida', 'Quimbaya', 'Montenegro'],
  'RIS': ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'La Virginia'],
  'SAP': ['San Andrés', 'Providencia'],
  'SAN': ['Bucaramanga', 'Floridablanca', 'Barrancabermeja', 'Girón', 'Piedecuesta', 'San Gil', 'Socorro'],
  'SUC': ['Sincelejo', 'Corozal', 'San Marcos', 'Tolú'],
  'TOL': ['Ibagué', 'El Espinal', 'Melgar', 'Chaparral', 'Líbano'],
  'VAC': ['Cali', 'Buenaventura', 'Palmira', 'Tuluá', 'Yumbo', 'Cartago', 'Jamundí', 'Buga', 'Candelaria', 'Florida', 'Pradera'],
  'VAU': ['Mitú'],
  'VID': ['Puerto Carreño', 'La Primavera']
};
